namespace Biovation.Brands.Virdi.UniComAPI
{
	public enum CallbackEventType : uint
	{
		None,
		Connected = 1601u,
		Disconnected,
		RealtimeAccessLog,
		GetAccessLog,
		GetAccessLogCount,
		AddUser = 1610u,
		DeleteUser,
		DeleteAllUser,
		GetUserCount,
		GetUserInfoList,
		GetUserData,
		VerifyUserAuthenticationInfo = 1620u,
		VerifyFinger1ToN,
		VerifyFinger1To1,
		VerifyCard,
		VerifyPassword,
		GetTerminalOption = 1630u,
		SetTerminalOption,
		FirmwareUpgrading = 1680u,
		FirmwareUpgraded,
		FirmwareVersion,
		UserFileUpgrading = 1685u,
		UserFileUpgraded,
		OpenDoor = 1690u,
		TerminalStatus,
		PictureLog = 1700u,
		Antipassback,
		SetAccessControlData,
		ControlPeripheralDevice = 1710u,
		GetTaFunction = 1720u,
		SetTaFunction,
		SetTaTime,
		GetTerminalMealConfig = 1730u,
		SetTerminalMealConfig,
		FingerImage = 1740u,
		PrivateMessage = 1750u,
		PublicMessage,
		SetSmartcardLayout = 1760u,
		SetWeigandFormat = 1765u
	}
}
