
namespace Biovation.Brands.Virdi.UniComAPI
{
    public enum VirdiError : uint
    {
        None,
        InvalidPointer,
        InvalidType,
        InvaklidParameter,
        InvalidData,
        FunctionFail,
        NotServerActive,
        InvalidTerminal,
        ProcessFail,
        UserCancel,
        UnknownReason = 16u,
        CodeSize = 513u,
        UserIdSize,
        UserNameSize,
        UniqueIDSize,
        InvalidSequrityLevel,
        PasswordSize,
        PictureSize,
        InvalidPictureType,
        RfIdSize,
        InvalidIndex = 528u,
        MaxCardNumber,
        MaxFingerNumber,
        MaxTimeZoneNumber,
        MaxHolidayNumber,
        MaxAccessTimeNumber,
        MaxAccessGroupNumber,
        InvalidUser = 769u,
        Unauthorized,
        Permission,
        FingerCaptureFail,
        DupAuthentication,
        AntiPasspsck,
        Network,
        ServerBusy,
        FaceDetection,
        UserRegistration = 1025u,
        FwResource,
        FwUpgrade,
        FwVersion,
        FreshMemory,
        NotFoundUser,
        SimilarFp,
        DuplicateUser,
        DuplicateRfId,
        Unknown = 4294967295u
    }
}
